name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: local
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up networking
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Init Terraform
        run: terraform init
      - name: Terraform plan
        run: terraform plan
